site_name: IHC Discord
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  favicon: assets/icons/favicon.ico
  logo: assets/icons/discord.png

pages:
    - Sobre o Projeto: index.md
    - Introdução: 
        - Planejamento: Introdução/Planejamento.md
        - Sobre o Discord: Introdução/Sobre_o_Discord.md
    - Desenvolvimento:
        - Questionário: Desenvolvimento/Questionário.md
        - Análise dos Dados: Desenvolvimento/Análise_dos_Dados.md
        - Prototipação: Desenvolvimento/Protótipo.md
    - Resultados:
        - Questionário: Resultados/Questionário.md
        - Análise dos Dados: Resultados/Análise_dos_Dados.md
        - Protótipo: Resultados/Prototipação.md
        - Conclusão: Resultados/Conclusão.md
    - Bibliografia: Bibliografia.md
